In [1]:
import pandas as pd

In [5]:

data = pd.read_csv("comptage-velo-donnees-compteurs.csv", sep=";")
data.head()

,Identifiant du compteur,Nom du compteur,Identifiant du site de comptage,Nom du site de comptage,Comptage horaire,Date et heure de comptage,Date d'installation du site de comptage,Lien vers photo du site de comptage,Coordonnées géographiques,Identifiant technique compteur,ID Photos,test_lien_vers_photos_du_site_de_comptage_,id_photo_1,url_sites,type_dimage,mois_annee_comptage
0,100003096-353242251,97 avenue Denfert Rochereau SO-NE,100003096,97 avenue Denfert Rochereau,14,2024-10-01T00:00:00+02:00,2012-02-22,https://filer.eco-counter-tools.com/file/10/6d...,"48.83504, 2.33314",Y2H21111072,https://filer.eco-counter-tools.com/file/10/6d...,https://filer.eco-counter-tools.com/file/10/6d...,https:,https://www.eco-visio.net/Photos/100003096,jpg,2024-10
1,100003096-353242251,97 avenue Denfert Rochereau SO-NE,100003096,97 avenue Denfert Rochereau,0,2024-10-01T03:00:00+02:00,2012-02-22,https://filer.eco-counter-tools.com/file/10/6d...,"48.83504, 2.33314",Y2H21111072,https://filer.eco-counter-tools.com/file/10/6d...,https://filer.eco-counter-tools.com/file/10/6d...,https:,https://www.eco-visio.net/Photos/100003096,jpg,2024-10
2,100003096-353242251,97 avenue Denfert Rochereau SO-NE,100003096,97 avenue Denfert Rochereau,9,2024-10-01T05:00:00+02:00,2012-02-22,https://filer.eco-counter-tools.com/file/10/6d...,"48.83504, 2.33314",Y2H21111072,https://filer.eco-counter-tools.com/file/10/6d...,https://filer.eco-counter-tools.com/file/10/6d...,https:,https://www.eco-visio.net/Photos/100003096,jpg,2024-10
3,100003096-353242251,97 avenue Denfert Rochereau SO-NE,100003096,97 avenue Denfert Rochereau,119,2024-10-01T10:00:00+02:00,2012-02-22,https://filer.eco-counter-tools.com/file/10/6d...,"48.83504, 2.33314",Y2H21111072,https://filer.eco-counter-tools.com/file/10/6d...,https://filer.eco-counter-tools.com/file/10/6d...,https:,https://www.eco-visio.net/Photos/100003096,jpg,2024-10
4,100003096-353242251,97 avenue Denfert Rochereau SO-NE,100003096,97 avenue Denfert Rochereau,106,2024-10-01T13:00:00+02:00,2012-02-22,https://filer.eco-counter-tools.com/file/10/6d...,"48.83504, 2.33314",Y2H21111072,https://filer.eco-counter-tools.com/file/10/6d...,https://filer.eco-counter-tools.com/file/10/6d...,https:,https://www.eco-visio.net/Photos/100003096,jpg,2024-10

In [7]:
data.describe()

       Identifiant du site de comptage  Comptage horaire
count                     9.900460e+05     990046.000000
mean                      1.329943e+08         77.401742
std                       7.418306e+07        107.557171
min                       1.000031e+08          0.000000
25%                       1.000475e+08         12.000000
50%                       1.000560e+08         42.000000
75%                       1.000563e+08         96.000000
max                       3.000303e+08       8190.000000

In [3]:
data.count()

Identifiant du compteur                       990046
Nom du compteur                               990046
Identifiant du site de comptage               990046
Nom du site de comptage                       990046
Comptage horaire                              990046
Date et heure de comptage                     990046
Date d'installation du site de comptage       990046
Lien vers photo du site de comptage           979852
Coordonnées géographiques                     990046
Identifiant technique compteur                979849
ID Photos                                     979852
test_lien_vers_photos_du_site_de_comptage_    979852
id_photo_1                                    979852
url_sites                                     990046
type_dimage                                   979852
mois_annee_comptage                           990046
dtype: int64

In [9]:
data.max()

TypeError: '>=' not supported between instances of 'str' and 'float'

In [7]:
data["Identifiant du compteur"].head

<bound method NDFrame.head of 0         100003096-353242251
1         100003096-353242251
2         100003096-353242251
3         100003096-353242251
4         100003096-353242251
                 ...
990041    300030271-353356061
990042    300030271-353356061
990043    300030271-353356061
990044    300030271-353356061
990045    300030271-353356061
Name: Identifiant du compteur, Length: 990046, dtype: object>

In [10]:
mask = data["Nom du site de comptage"]== "*Magenta*"

data[mask]

Empty DataFrame
Columns: [Identifiant du compteur, Nom du compteur, Identifiant du site de comptage, Nom du site de comptage, Comptage horaire, Date et heure de comptage, Date d'installation du site de comptage, Lien vers photo du site de comptage, Coordonnées géographiques, Identifiant technique compteur, ID Photos, test_lien_vers_photos_du_site_de_comptage_, id_photo_1, url_sites, type_dimage, mois_annee_comptage]
Index: []

In [11]:
data["Nom du site de comptage"].unique()

array(['97 avenue Denfert Rochereau', '105 rue La Fayette',
       '106 avenue Denfert Rochereau', '135 avenue Daumesnil',
       '100 rue La Fayette', '28 boulevard Diderot',
       '39 quai François Mauriac', "18 quai de l'Hôtel de Ville",
       '27 boulevard Diderot', 'Voie Georges Pompidou',
       '67 boulevard Voltaire', '10 avenue de la Grande Armée',
       '7 avenue de la Grande Armée', '72 boulevard Voltaire',
       '89 boulevard de Magenta', '16 avenue de la Porte des Ternes',
       'Pont du Garigliano', '102 boulevard de Magenta',
       'Face au 16 avenue de la  Porte des Ternes',
       '21 boulevard Auguste Blanqui', '72 boulevard Richard Lenoir',
       'Pont National', 'Face au 48 quai de la marne',
       '77 boulevard Richard Lenoir', "Face 104 rue d'Aubervilliers",
       'Face au 70 quai de Bercy', '6 rue Julia Bartet',
       "Face au 25 quai de l'Oise", '35 boulevard de Ménilmontant',
       '152 boulevard du Montparnasse', '10 boulevard Auguste Blanqui',
       '243 boulevard Saint Germain', 'Totem 64 Rue de Rivoli',
       '87 avenue de Flandre', '72 avenue de Flandre',
       '44 avenue des Champs Elysées', "180 avenue d'Italie",
       '129 rue Lecourbe', "147 avenue d'Italie",
       '33 avenue des Champs Elysées', '132 rue Lecourbe',
       'Pont de la Concorde', 'Pont des Invalides',
       'Face au 8 avenue de la porte de Charenton',
       'Face au 4 avenue de la porte de Bagnolet',
       'Pont Charles De Gaulle', '36 quai de Grenelle',
       "Face au 40 quai D'Issy", 'Pont de Bercy', '38 rue Turbigo',
       "Quai d'Orsay", '27 quai de la Tournelle',
       "Totem 85 quai d'Austerlitz", 'Totem Cours la Reine',
       'Totem 73 boulevard de Sébastopol', '21 boulevard Saint Michel',
       'Quai des Tuileries', '9 boulevard Jourdan',
       '24 boulevard Jourdan', '27 boulevard Davout',
       '42 boulevard Soult', '51 boulevard du Général Martial Valin',
       '56 boulevard Kellermann', '72 boulevard Brune',
       '77 boulevard Masséna', '81 boulevard Mortier',
       '98 boulevard Poniatowski', '163 boulevard Brune',
       'Face au 49 boulevard du Général Martial Valin'], dtype=object)

In [14]:
mask = data["Nom du site de comptage"]=="102 boulevard de Magenta"

data_magenta = data[mask]
mask = data["Nom du site de comptage"]=="81 boulevard Mortier"

data_mortier = data[mask]

In [15]:
print(data_magenta["Comptage horaire"].sum())

print(data_mortier["Comptage horaire"].sum())

2263947
519867